// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfKiE9hoRSJIqvatWzdESfgFnsTiKDIFc',
    appId: '1:140530809923:web:c9d4c40bf6a1aa8614a8f6',
    messagingSenderId: '140530809923',
    projectId: 'tccalimentracker',
    authDomain: 'tccalimentracker.firebaseapp.com',
    storageBucket: 'tccalimentracker.appspot.com',
    measurementId: 'G-FHW6F87KEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0BtaGhq3hCqJapMvyZ9S5VQ3QCR-_A28',
    appId: '1:140530809923:android:ed6a5bd919e4758f14a8f6',
    messagingSenderId: '140530809923',
    projectId: 'tccalimentracker',
    storageBucket: 'tccalimentracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrBjHey97VNzrs-xymycKZUbD5qvP2ChQ',
    appId: '1:140530809923:ios:d8803926e2a68cf114a8f6',
    messagingSenderId: '140530809923',
    projectId: 'tccalimentracker',
    storageBucket: 'tccalimentracker.appspot.com',
    iosBundleId: 'com.example.alimentracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrBjHey97VNzrs-xymycKZUbD5qvP2ChQ',
    appId: '1:140530809923:ios:d8803926e2a68cf114a8f6',
    messagingSenderId: '140530809923',
    projectId: 'tccalimentracker',
    storageBucket: 'tccalimentracker.appspot.com',
    iosBundleId: 'com.example.alimentracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfKiE9hoRSJIqvatWzdESfgFnsTiKDIFc',
    appId: '1:140530809923:web:6e2dbc6dddea423b14a8f6',
    messagingSenderId: '140530809923',
    projectId: 'tccalimentracker',
    authDomain: 'tccalimentracker.firebaseapp.com',
    storageBucket: 'tccalimentracker.appspot.com',
    measurementId: 'G-FHQ1NKFVLV',
  );
}
